import LegalLayout from '../components/LegalLayout'
import '../components/LegalLayout.css'

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy" subtitle="Legal">
      <div className="legal-content">

        <section>
          <h2><span className="legal-num">01</span> General Information</h2>
          <p>
            Protecting your personal data is important to us. This Privacy Policy explains how
            Eden-Core collects, uses, and protects personal information when you visit our website
            or contact us.
          </p>
          <p>
            By using this website, you agree to the practices described in this policy.
          </p>
        </section>

        <section>
          <h2><span className="legal-num">02</span> Responsible Entity</h2>
          <div className="legal-info-card">
            <p><strong>Eden-Core</strong></p>
            <p>Rothenburg, Lucerne</p>
            <p>Switzerland</p>
            <p>E-Mail: <a href="mailto:info@eden-core.com">info@eden-core.com</a></p>
          </div>
        </section>

        <section>
          <h2><span className="legal-num">03</span> Collection of Personal Data</h2>
          <p>We may collect personal data when you:</p>
          <ul>
            <li>visit our website</li>
            <li>fill out contact forms</li>
            <li>send us an email</li>
            <li>request a quote or consultation</li>
            <li>interact with website features</li>
          </ul>
          <p>The data collected may include:</p>
          <ul>
            <li>name</li>
            <li>email address</li>
            <li>company name</li>
            <li>phone number</li>
            <li>IP address</li>
            <li>browser and device information</li>
            <li>website usage data</li>
          </ul>
        </section>

        <section>
          <h2><span className="legal-num">04</span> Cookies</h2>
          <p>
            Our website uses cookies and similar technologies to improve user experience,
            analyze website traffic, and optimize our services.
          </p>
          <p>Cookies are small text files stored on your device.</p>
          <p>You can control or disable cookies through your browser settings.</p>
          <p>
            Please note that disabling cookies may affect certain website functionalities.
          </p>
        </section>

        <section>
          <h2><span className="legal-num">05</span> Google Analytics</h2>
          <p>
            This website uses Google Analytics, a web analytics service provided by Google LLC.
          </p>
          <p>
            Google Analytics uses cookies to analyze how visitors use the website.
            Information generated by these cookies may include:
          </p>
          <ul>
            <li>pages visited</li>
            <li>time spent on pages</li>
            <li>device and browser information</li>
            <li>approximate geographic location</li>
            <li>interaction behavior</li>
          </ul>
          <p>IP anonymization may be enabled where applicable.</p>
          <p>
            The information collected may be transmitted to and stored on servers operated by Google.
          </p>
          <p>You can prevent the collection of data by Google Analytics by:</p>
          <ul>
            <li>adjusting your cookie settings</li>
            <li>using browser extensions that block tracking technologies</li>
          </ul>
          <p>
            More information:{' '}
            <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">
              https://policies.google.com/privacy
            </a>
          </p>
        </section>

        <section>
          <h2><span className="legal-num">06</span> Contact Forms & Communication</h2>
          <p>
            If you contact us via contact form or email, the information you provide will be
            stored for the purpose of processing your request and potential follow-up communication.
          </p>
          <p>We do not sell personal data to third parties.</p>
        </section>

        <section>
          <h2><span className="legal-num">07</span> Hosting & Technical Providers</h2>
          <p>
            Our website may be hosted through third-party infrastructure providers. Technical data
            such as IP addresses, browser information, and server logs may be processed for security
            and operational purposes.
          </p>
          <p>We work with providers that implement appropriate security measures.</p>
        </section>

        <section>
          <h2><span className="legal-num">08</span> Data Retention</h2>
          <p>
            Personal data is retained only as long as necessary for the purposes described in this
            policy or as required by applicable law.
          </p>
        </section>

        <section>
          <h2><span className="legal-num">09</span> Your Rights</h2>
          <p>Depending on applicable law, you may have the right to:</p>
          <ul>
            <li>request access to your personal data</li>
            <li>request correction of inaccurate data</li>
            <li>request deletion of your data</li>
            <li>object to certain processing activities</li>
            <li>withdraw consent where applicable</li>
          </ul>
          <p>Requests can be submitted via email.</p>
        </section>

        <section>
          <h2><span className="legal-num">10</span> Data Security</h2>
          <p>
            We implement reasonable technical and organizational measures to protect personal data
            against unauthorized access, loss, misuse, or disclosure.
          </p>
          <p>However, no method of online transmission or storage is completely secure.</p>
        </section>

        <section>
          <h2><span className="legal-num">11</span> External Links</h2>
          <p>
            Our website may contain links to external websites. We are not responsible for the
            privacy practices or content of third-party websites.
          </p>
        </section>

        <section>
          <h2><span className="legal-num">12</span> Changes to This Privacy Policy</h2>
          <p>
            We may update this Privacy Policy from time to time to reflect legal, technical, or
            operational changes.
          </p>
          <p>The latest version published on this website shall apply.</p>
        </section>

        <section>
          <h2><span className="legal-num">13</span> Contact</h2>
          <p>For questions regarding this Privacy Policy or data protection matters, please contact:</p>
          <div className="legal-info-card">
            <p><strong>Eden-Core</strong></p>
            <p>E-Mail: <a href="mailto:info@eden-core.com">info@eden-core.com</a></p>
          </div>
        </section>

      </div>
    </LegalLayout>
  )
}
